### ISSUE TITLE
All folders are empty

### ISSUE THREAD

**Issue by vnckppl** [mkcms/mu4e-overview#8]
mu4e-overview shows all nested folders, but indicates that they are all empty: [0/0] 
Is this a known issue?

**Comment by mkcms** [comment]
No, I've never seen this behavior. Can you provide more details?

Did you index your maildir? (`mu4e-update-index`)
What mu/mu4e version do you use?

**Comment by vnckppl** [comment]
Thank you for your reply. I am not sure what is happening. Currently, mu4e-overview remains empty entirely. When I call mu4e-overview, it does show the message 'updating maildir status'. I have over a hundred folders in my maildir. Could that be an issue?

**Comment by mkcms** [comment]
What mu/mu4e version do you have? And what OS? If you have Windows, it won'twork. I would like it to work on Windows, but unfortunately I don't have a Windows machine to test this package on.

> I have over a hundred folders in my maildir. Could that be an issue?

Maybe. Perhaps it's a resource exhaustion issue. `mu4e-overview` runs a bunch of processes for each folder in parallel. If you have hundreds of folders, it means it will start hundreds of processes and kill them after a timeout.

Can you try this patch, and see if it makes any difference? 

```diff
diff --git a/mu4e-overview.el b/mu4e-overview.el
index af582b3..ee786b9 100644
--- a/mu4e-overview.el
+++ b/mu4e-overview.el
@@ -189,7 +189,7 @@ passed to CALLBACK will be 0."
         (push process mu4e-overview--processes)
 
         ;; Kill this process after some time.
-        (run-with-timer 10.0 nil #'delete-process process)))))
+        (run-with-timer 30.0 nil #'delete-process process)))))
 
 (defun mu4e-overview-update ()
   "Update the list of maildirs and count the number of unread/total messages."
```

**Comment by vnckppl** [comment]
Yes, of course:
mu version 1.4.12
emacs version 26.3
MacOS Mojave 10.14.6

I set the timer to 60 seconds just to be sure, but that did not fix it, unfortunately. 
I have been logging the error messages and did notice this:

```
Updating maildir status...
error in process filter: apply: Creating pipe: Too many open files
error in process filter: Creating pipe: Too many open files
Updating maildir status...38%
```

**Comment by mkcms** [comment]
Thanks for the logs. My intuition tells me that indeed there are too many processes being launched simultaneously. What I think this means is I will have to rewrite some of the code to use some kind of a process pool, so that at any point in time there is a fixed maximum amount of live processes. I will try to do something this weekend.

In the meantime, perhaps you can try running Emacs with increased limits, namely maximum number of open file descriptors. I don't know how to do it on MacOS, but on Linux you can use `ulimit` command and others.

Also, is it possible for you to check if this problem is also present if you run bare Emacs (without your init file) and with only mu4e and mu4e-overview installed?

**Comment by mkcms** [comment]
Sorry, unfortunately I was not able to get to it last weekend, but I just pushed a fix in  5e69f0b.
This limits the number of processes spawned, so that at any point in time there are no more than `mu4e-overview-parallel-processes`. You can make that variable higher to improve refresh times; or lower to prevent reaching open file limit on your system at the cost of speed.

Can you test this again? Thank you.

**Comment by vnckppl** [comment]
Alright! This fixed the issue with mu4e not showing anything. Now, the window with folders is being shown again. However, the folders still all show as empty '[0/0].
FYI, I just updated to emacs 27.1, but I have the same issue there.

**Comment by mkcms** [comment]
> However, the folders still all show as empty '[0/0].

:-(

Can you reproduce this with `emacs -Q` and only this package installed? (and mu4e of course)
Also, I have mu version 1.2.0, maybe I will try to build newer version from sources and try again.

**Comment by mkcms** [comment]
> Also, I have mu version 1.2.0, maybe I will try to build newer version from sources and try again.

I tried with mu/mu4e 1.4.12, I see no issues.

**Comment by vnckppl** [comment]
I ran emacs -Q with only mu4e, mu4e-overview, and use-package enabled, but this did not resolve the issue (folders still show empty [0/0]. Interestingly, when I run mu4e-overview on Debian under Emacs 26.1, with the same init file and mbsync init file the correct number of mails show up for each folder under mu4e-overview.

**Comment by mkcms** [comment]
Do you see the same error messages as you saw before (`error in process filter: apply: Creating pipe: Too many open files`)?

**Comment by vnckppl** [comment]
No, I don't. But that had to do with the mu4e-overview not showing up at all anymore, right? mu4e-overview shows the correct tree of accounts and folders (and subfolders), but they just are labeled empty [0/0]. When I go into the mu4e-overview buffer, I can click on the folder names and I will be directed to the correct mu4e folder buffer.

**Comment by mkcms** [comment]
I just noticed an error in the code which also causes some folders to show as `[0/0]` for me. This only happens for folders that have a space character in their name, but maybe some other characters cause this problem as well. Maybe you have folders with whitespace/nonstandard characters in their name?

**Comment by mkcms** [comment]
I just pushed a commit that fixes the same problem for another user. @vnckppl Could you check?

**Comment by vnckppl** [comment]
@mkcms I am no longer using mu4e-overview, but I do appreciate the heads up.
